baseurl = "https://pluggedcomputing.gitlab.io"
contentdir    = "content"
layoutdir     = "layouts"
publishdir    = "public"
title = "Plugged Computing"
canonifyurls  = true

DefaultContentLanguage = "pt"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsUseClasses = true
pygmentCodeFences = true
#disqusShortname = "XXX"
#googleAnalytics = "XXX"

[Params]
  subtitle = "Documentação de Referencia"
  logo = "img/avatar-icon.png"
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  name = "Matheus Barbosa de Oliveira"
  email = "matheus.barbosa@dcx.ufpb.br"
  gitlab = "barbosamaatheus"
  github = "barbosamaatheus"
  twitter = "barbosamaatheus"
  instagram = "barbosamaatheus"

[[menu.main]]
    name = "Inicio"
    url = ""
    weight = 1

[[menu.main]]
    identifier = "environment"
    name = "Configurações de Ambiente"
    weight = 2

[[menu.main]]
    parent = "environment"
    name = "Pré Requisitos"
    url = "post/environment_settings/pre_requirements"
    weight = 1

[[menu.main]]
    parent = "environment"
    name = "Java JDK"
    url = "post/environment_settings/environment_java"
    weight = 2

[[menu.main]]
    parent = "environment"
    name = "Android SDK"
    url = "post/environment_settings/environment_android"
    weight = 3

[[menu.main]]
    parent = "environment"
    name = "Outras Variaveis"
    url = "post/environment_settings/environment_others"
    weight = 4

[[menu.main]]
    parent = "environment"
    name = "Instalando Dependencias"
    url = "post/environment_settings/installing_dependencies"
    weight = 5

[[menu.main]]
    parent = "environment"
    name = "Testando"
    url = "post/environment_settings/testing"
    weight = 6
    

[[menu.main]]
    name = "Contribuições"
    url = "page/contribution/"
    weight = 3
